---
############################################
# Support local development with podman
#   podman play kube ./container/otel-frontend.yaml
############################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: otel
  name: otel-frontend
spec:
  containers:
  - image: docker.io/otel/opentelemetry-collector:0.50.0
    name: otel-collector
    ports:
    - containerPort: 13133
      hostPort: 13133
    - containerPort: 4317
      hostPort: 4317
    - containerPort: 55680
      hostPort: 55680
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - name: config
      mountPath: /etc/otel-collector-config.yaml
  restartPolicy: Always
  volumes:
  - name: config
    hostPath: # podman play kube supports hostPath and PVC volume only 
      path: ./.container/otel-collector-config.yaml
      type: File
...