receivers:
  otlp:
    protocols:
      grpc:
        # By default listening on 4317 port
        # endpoint: 0.0.0.0:4317
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
exporters:
  jaeger:
    # Collector and Jaeger platform are running in the same Pod
    endpoint: 0.0.0.0:14250
    # Collector container may be started faster than 
    # the backend Jaeger platform
    retry_on_failure:
      enabled: true
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp,otlp/2]
      # receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]