---
############################################
# Support local development with podman
#   podman play kube ./container/otel-backend.yaml
############################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: otel
  name: otel-backend
spec:
  containers:
  - image: docker.io/jaegertracing/all-in-one:latest
    name: jaeger-all-in-one
    ports:
    - containerPort: 16686
      hostPort: 16686
    - containerPort: 14268
      hostPort: 14268
    - containerPort: 14250
      hostPort: 14250
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Never
  volumes:
  - name: config
    hostPath: # podman play kube supports hostPath and PVC volume only 
      path: ./.container/otel-collector-config.yaml
      type: File
...