---
############################################
# Support local development with podman
#   podman kube play ./.container/otel.yaml
############################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: otel
  name: otel
spec:
  containers:
  - image: docker.io/jaegertracing/all-in-one:latest
    name: jaeger-all-in-one
    ports:
    - containerPort: 16686
      hostPort: 16686
    - containerPort: 14268
      hostPort: 14268
    - containerPort: 14250
      hostPort: 14250
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - image: docker.io/otel/opentelemetry-collector:latest
    name: collector
    args:
      - "--config=/etc/otel-collector-config.yaml"
    ports:
    - containerPort: 13133
      hostPort: 13133
    - containerPort: 4317
      hostPort: 4317
    - containerPort: 55680
      hostPort: 55680
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - name: config
      mountPath: /etc/otel-collector-config.yaml
  restartPolicy: Always
  volumes:
  - name: config
    hostPath: # podman play kube supports hostPath and PVC volume only 
      path: ./.container/otel-collector-config.yaml
      type: File
...
